In [7]:
print(f"'Origin序号'列: {df1['Origin序号'].isna().sum()} 个NaN")
print(f"'秒序号'列: {df1['秒序号'].isna().sum()} 个NaN")

print(f"'Origin序号'列: {df2['Origin序号'].isna().sum()} 个NaN")
print(f"'秒序号'列: {df2['秒序号'].isna().sum()} 个NaN")

'Origin序号'列: 0 个NaN
'秒序号'列: 0 个NaN
'Origin序号'列: 530176 个NaN
'秒序号'列: 530176 个NaN

In [8]:
import pandas as pd

df1 = pd.read_csv('314_326.csv')

df2 = pd.read_csv('326-331.csv')

df_merged = pd.concat([df1, df2], ignore_index=True)

df_merged = df_merged.dropna(subset=['Origin序号', '秒序号'])

if 'Origin序号' in df_merged.columns:
    df_merged['Origin序号'] = df_merged['Origin序号'].astype(int)

if '秒序号' in df_merged.columns:
    df_merged['秒序号'] = df_merged['秒序号'].astype(int)

df_merged.to_csv('month_3.csv', index=False)

print(f"合并完成")

C:\Users\47226\AppData\Local\Temp\ipykernel_22988\2967317795.py:5: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('326-331.csv')

合并完成

In [ ]:
import pandas as pd
import numpy as np
from datetime import datetime

df = pd.read_csv('month_3.csv')

df['每日对应秒序号'] = df['秒序号']

try:
    df['记录仪时间'] = pd.to_datetime(df['记录仪时间'])
except:
    # 格式为 yyyy-mm-dd HH:MM:SS
    try:
        df['记录仪时间'] = pd.to_datetime(df['记录仪时间'], format='%Y-%m-%d %H:%M:%S')
    except:
        print("无法转换记录仪时间列，请检查日期格式并修改代码中的format参数")

df['年'] = df['记录仪时间'].dt.year
df['月'] = df['记录仪时间'].dt.month
df['日'] = df['记录仪时间'].dt.day
df['小时'] = df['记录仪时间'].dt.hour
df['分钟'] = df['记录仪时间'].dt.minute

df['日期'] = df['记录仪时间'].dt.date

df['每日对应秒序号'] = df.groupby('日期').cumcount()

df.to_csv('month_3_processed.csv', index=False)

print("处理完成！新文件已保存为month_3_processed.csv")

处理完成！新文件已保存为month_3_processed.csv
                记录仪时间     年  月   日  小时  分钟  秒序号  每日对应秒序号
0 2021-03-14 16:00:00  2021  3  14  16   0    0        0
1 2021-03-14 16:00:00  2021  3  14  16   0    1        1
2 2021-03-14 16:00:00  2021  3  14  16   0    2        2
3 2021-03-14 16:00:00  2021  3  14  16   0    3        3
4 2021-03-14 16:00:00  2021  3  14  16   0    4        4
5 2021-03-14 16:00:00  2021  3  14  16   0    5        5
6 2021-03-14 16:00:00  2021  3  14  16   0    6        6
7 2021-03-14 16:00:00  2021  3  14  16   0    7        7
8 2021-03-14 16:00:00  2021  3  14  16   0    8        8
9 2021-03-14 16:00:00  2021  3  14  16   0    9        9

In [4]:
df[['记录仪时间', '年', '月', '日', '小时', '分钟', '秒序号', '每日对应秒序号']].head(10)

                记录仪时间     年  月   日  小时  分钟  秒序号  每日对应秒序号
0 2021-03-14 16:00:00  2021  3  14  16   0    0        0
1 2021-03-14 16:00:00  2021  3  14  16   0    1        1
2 2021-03-14 16:00:00  2021  3  14  16   0    2        2
3 2021-03-14 16:00:00  2021  3  14  16   0    3        3
4 2021-03-14 16:00:00  2021  3  14  16   0    4        4
5 2021-03-14 16:00:00  2021  3  14  16   0    5        5
6 2021-03-14 16:00:00  2021  3  14  16   0    6        6
7 2021-03-14 16:00:00  2021  3  14  16   0    7        7
8 2021-03-14 16:00:00  2021  3  14  16   0    8        8
9 2021-03-14 16:00:00  2021  3  14  16   0    9        9